query pageQuery {
  ...LayoutQueryFragment
  postConnection {
    edges {
      node {
        ... on Document {
          id
          _values
          _sys {
            filename
          }
        }
        ... on PostBlog1 {
          author {
            ... on Author {
              ...AuthorParts
            }
          }
        }
      }
    }
  }
}

query contentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  page(relativePath: $relativePath) {
    ...PageParts
  }
}

query blogPostQuery($relativePath: String!) {
  ...LayoutQueryFragment
  post(relativePath: $relativePath) {
    ...PostParts
    ... on PostBlog1 {
      author {
        ... on Author {
          name
          avatar
        }
      }
    }
  }
}
